language: python
python:
  - 3.7
env:
  - DJANGO=3.0
services:
  - docker
before_script:
  - pip install docker-compose
script:
  - docker-compose -f docker-compose.travis.yml up --build -d
  - docker ps
  - docker exec web coverage run -m pytest
after_success:
  - docker exec web coverage report
  - docker exec web coveralls
notifications:
  email:
    on_success: change
    on_failure: always
