language: python
python:
  - 3.7
env:
  - DJANGO=3.0
services:
  - docker
before_script:
  - pip install docker-compose
script:
  - docker-compose -f docker-compose.travis.yml run web sh -c "coverage run -m pytest"
after_success:
  - docker-compose -f docker-compose.travis.yml run web sh -c "coverage report"
  - docker-compose -f docker-compose.travis.yml run web sh -c "coveralls"
notifications:
  email:
    on_success: change
    on_failure: always
