language: python
python:
  - 3.7
env:
  - DJANGO=3.0
before_install:
  - export DJANGO_SETTINGS_MODULE="intranet.settings.travis"
  - export DEBUG=True
install:
  - pip install coverage
  - pip install coveralls
  - pip install -r intranet/requirements.txt
script:
  - cd intranet
  - coverage run -m pytest
after_success:
  - coverage report
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: always
