language: python
python:
  - 3.7
env:
  - DJANGO=3.0
services:
  - docker
before_script:
  - pip install docker-compose
script:
  - docker-compose -f docker-compose.travis.yml up --build -d
  - docker ps -a
  - docker exec intranet_web_1 coverage run -m pytest
after_success:
  - docker exec intranet_web_1 coverage report
  - docker exec intranet_web_1 coveralls
notifications:
  email:
    on_success: change
    on_failure: always
