version: '3.2'

services:
  web:
    env_file:
      - /Users/$USER/intranet_web.env
    build: intranet/
    container_name: web
    volumes:
      - ./intranet:/code
      - static_volume:/code/static
      - media_volume:/code/media
      - /Users/$USER/Box/RBG-Shared:/Box:ro
    expose:
      - '8000'
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: python /code/manage.py runserver 0.0.0.0:8000
  db:
    image: "postgres:11"
    container_name: db
    env_file:
      - /Users/$USER/intranet_db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./targets.json:/etc/prometheus/targets.json:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - web

  # Snipe-it Containers
  snipe-mysql:
    container_name: snipe-mysql
    image: mysql:5.6
    env_file:
      - /Users/$USER/intranet_snipe-it.env
    volumes:
      - snipesql-vol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"

  snipe-it:
    image: snipe/snipe-it:v4.9.3
    env_file:
      - /Users/$USER/intranet_snipe-it.env
    ports:
      - "3051:80"
    depends_on:
      - snipe-mysql

volumes:
  postgres_data:
  static_volume:
  media_volume:
  snipesql-vol:
