version: '3'

services:
  web:
    environment:
      - PG_PASSWORD
      - PG_USER
      - PG_DB
    build: intranet/
    volumes:
      - ./intranet:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - '8000'
    depends_on:
      - db
  db:
    image: "postgres:11"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
