version: '3'

services:
  web:
    env_file:
      - /Users/$USER/intranet_web.env
    build: intranet/
    volumes:
      - ./intranet:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - '8000'
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: "postgres:11"
    env_file:
      - /Users/$USER/intranet_db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
