global:
  scrape_interval: 1m
  evaluation_interval: 1m

rule_files:
  - 'django_rules'

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: 'node'
    file_sd_configs:
      - files:
          - 'targets.json'
  - job_name: 'django'
    tls_config:
      cert_file: /etc/ssl/certs/intranet_redbutte_utah_edu_cert.cer
      key_file: /etc/ssl/certs/intranet.key
      server_name: intranet.redbutte.utah.edu
    metrics_path: /monitoring/metrics
    static_configs:
      - targets: ['intranet.redbutte.utah.edu']
      - targets:
          - web:8000
